### ISSUE TITLE
Pluggy 1.1.0 makes conda fail

### ISSUE THREAD

**Issue by juanfcocontreras** [conda-forge/pluggy-feedstock#34]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In a clean environment, when update to pluggy 1.1.0:

```
  Package   Version  Build         Channel         Size
─────────────────────────────────────────────────────────
  Upgrade:
─────────────────────────────────────────────────────────

  - pluggy    1.0.0  pyhd8ed1ab_5  conda-forge
  + pluggy    1.1.0  pyhd8ed1ab_0  conda-forge     21kB
```

It makes conda unusable in a Mac Apple M2:

```
KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/exception_handler.py", line 16, in __call__
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/main.py", line 70, in main_subshell
    p = generate_parser()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 65, in generate_parser
    p = ArgumentParser(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 152, in __init__
    self._subcommands = context.plugin_manager.get_hook_results("subcommands")
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/plugins/manager.py", line 104, in get_hook_results
    (item for items in hook() for item in items),
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/exception_handler.py", line 165, in print_unexpected_error_report
    get_main_info_str(error_report["conda_info"])
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/main_info.py", line 250, in get_main_info_str
    info_dict["_" + key] = ("\n" + 26 * " ").join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/main.py", line 70, in main_subshell
        p = generate_parser()
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 65, in generate_parser
        p = ArgumentParser(
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 152, in __init__
        self._subcommands = context.plugin_manager.get_hook_results("subcommands")
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/plugins/manager.py", line 104, in get_hook_results
        (item for items in hook() for item in items),
    TypeError: 'NoneType' object is not iterable

`$ /opt/homebrew/Caskroom/miniforge/base/bin/conda list`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: n

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

### Installed packages

```shell
Can't run `conda list`
```

### Environment info

```shell
Can't run `conda info`
```

**Comment by nicoddemus** [comment]
Actually let's keep this open, as others with the same problem might land here.
